# Generated by Django 5.0.6 on 2024-05-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
    ]
